name: Deploy Storybook

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "apps/storybook/**"
      - "packages/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "turbo.json"
      - ".github/workflows/deploy-storybook.yml"
      - "tooling/github/setup/**"

concurrency:
  group: deploy-storybook
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Copy env
        shell: bash
        run: cp .env.example .env

      - name: Build Storybook
        run: pnpm exec turbo run build --filter=@notion-kit/storybook

      - uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: apps/storybook/storybook-static
          retention-days: 1
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: [self-hosted, storybook]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: storybook-static
          path: storybook-static

      - name: Publish
        run: rsync -a --delete storybook-static/ /var/www/storybook/
